### ISSUE TITLE
Pagina de Ranking

### ISSUE THREAD

**Issue by emilianobilli** [cryptospaceship/backend#7]
- [x] Al abandonar el juego, el CSS Token sigue estando y muchas muchos CSS Token del mismo jugador

![image](https://user-images.githubusercontent.com/12865333/53881829-67a54d00-3ff3-11e9-923a-13163bf20ad2.png)

- [x] Al hacer click sobre su propio CSS Token abrir modal y mostrar las siguientes estadisticas: (Gas utilizado, Gas x Gas Price, Cantidad de transacciones)

**Comment by nicolaspajoni** [comment]
Ya está hecha la url de consulta para el punto 2: /api/ship/stats/<game_id>/
Devuelve un json con el siguiente formato: {"transactions": 2, "gas": 693172}

**Comment by emilianobilli** [comment]
Tengo quilombos para hacer el blur de la pagina

**Comment by nicolaspajoni** [comment]
Faltaba poner el tag "main" en el html. Ya funciona.
